CODE SEGMENTASSUME CS : CODE , DS : CODE , ES  : CODE , SS : CODE
PPI EQU 26H
CPORT EQU  24HBPORT EQU 22H
APORT EQU 20H
ORG 1000H
;IF YOU IN FLOOR 2 , PRESS B1 => GO TO FLOOR 1
MOV AL , 90HOUT PPI , AL
AGAIN :
IN AL, APORTCMP AL , 2EH    ; IF YOU IN FLOOR 2 & PRESS 1
JNE AGAIN
;; GO TO FLOOR 1
MOV AL , 0F9HOUT CPORT , AL

REPEAT :IN AL , APORT
AND AL , 0F0H
CMP AL , 10HJE IN_1
JMP REPEAT
IN_1 :
      ;; STOP GO DOWN      MOV AL, 0EFH
      OUT CPORT , AL      IN AL , APORT
      ;; PRESS F3      CMP AL, 1BH
      JE GO_2      ;; PRESS F2
      CMP AL, 1DH      JE GO_2
      JMP IN_1      

EXIT :      MOV AL , 0EFH
      OUT CPORT , AL
GO_2 :     ;; GO UP
      MOV AL , 0F6H      OUT CPORT , AL
      REPEAT_2 :
      IN AL , APORT      AND AL , 0F0H
      CMP AL , 20H      JE IN_2
      JMP REPEAT_2      
     IN_2 :
      MOV AL, 0DFH
      OUT CPORT , AL       JMP AGAIN
      INT 3;      CODE ENDS
      END